FROM python:3.10-slim

WORKDIR /app


# Copy requirements
COPY requirements.txt .


# Install deps
RUN pip install --no-cache-dir -r requirements.txt


# Copy project files
COPY backend/ backend/
COPY models/ models/
COPY data/ data/


WORKDIR /app/backend


EXPOSE 5000


CMD ["python", "app.py"]
